services:
  postgres:
    image: postgres:16
    ports:
      - "5431:5432" # Correct format for port mapping
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data # Correct format for volume mapping

volumes:
  postgres_data:
